# Generated by Django 5.1.7 on 2025-03-25 05:16

import Notemarks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notemarks', '0003_alter_book_cover_image_alter_book_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notemark',
            name='tag',
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=models.ManyToManyField(blank=True, to='Notemarks.tag'),
        ),
        migrations.AddField(
            model_name='notemark',
            name='tags',
            field=models.ManyToManyField(blank=True, to='Notemarks.tag'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=Notemarks.models.upload_cover_image),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
