# Generated by Django 5.1.7 on 2025-03-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notemarks', '0005_alter_book_cover_image_alter_book_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notemark',
            name='contents',
            field=models.CharField(blank=True, max_length=32000),
        ),
    ]
