# Generated by Django 5.1.7 on 2025-03-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notemarks', '0007_notemark_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='notemark',
            name='color',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7),
        ),
    ]
