# Generated by Django 5.1.7 on 2025-04-07 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notemarks', '0009_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
