# Generated by Django 5.1.7 on 2025-04-07 14:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notemarks', '0010_delete_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='author_email',
            field=models.EmailField(blank=True, help_text="The author's email address.", max_length=255, null=True, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AddField(
            model_name='book',
            name='book_pdf',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
