# Generated by Django 5.1.7 on 2025-04-08 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notemarks', '0011_book_author_email_book_book_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='tags',
        ),
    ]
